apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cysl
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CoastalYouthSoccer/helm-charts.git
    targetRevision: finalize-templates
    path: charts/cysl-api
    helm:
      values: |
        replicaCount: 1
        image:
          tag: add-association-officers-venue-rules
        envFile: "/opt/cysl/api/cysl-env"
  destination:
    server: https://kubernetes.default.svc
    namespace: cysl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

