apiVersion: v1
kind: ConfigMap
metadata:
  name: kopf-ssl-patch
  namespace: mysql-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  sitecustomize.py: |
    import ssl
    import aiohttp

    # Create unverified SSL context
    _original_create_default_context = ssl.create_default_context

    def _create_unverified_context(*args, **kwargs):
        context = _original_create_default_context(*args, **kwargs)
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        return context

    ssl.create_default_context = _create_unverified_context
    ssl._create_default_https_context = ssl._create_unverified_context
