apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    repoURL: https://mysql.github.io/mysql-operator/
    chart: mysql-operator
    targetRevision: 2.2.5

  helm:
    # Override values to disable SSL verification (workaround for MicroK8s)
    values: |
      # Skip SSL verification for MicroK8s compatibility
      podAnnotations:
        microk8s.io/ssl-verify: "false"
        
      # Add environment variable to operator
      env:
      - name: PYTHONHTTPSVERIFY
        value: "0"
      - name: CURL_CA_BUNDLE
        value: ""
      - name: REQUESTS_CA_BUNDLE
        value: ""
  
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  # Wait for CRDs to be established
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
