apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # After operator
spec:
  project: default
  
  source:
    repoURL: https://github.com/erikdeirdre/argocd.git
    targetRevision: main
    path: apps/databases/mysql-cluster
  
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true  # Critical!
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
  
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
