apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
destination:
  name: ''
  namespace: "{namespace}"
  server: 'https://kubernetes.default.svc'
source:
  path: ''
  repoURL: 'https://grafana.github.io/helm-charts'
  targetRevision: ''
  chart: k8s-monitoring
  helm:
    valuesObject:
      cluster:
        name: main

        externalServices:
          prometheus:
            hostKey: prometheus-url
            basicAuth:
              usernameKey: username
              passwordKey: password
            secret:
              name: grafana-cloud-credentials
              namespace: monitoring
          loki:
            hostKey: loki-url
            basicAuth:
              usernameKey: username
              passwordKey: password
            secret:
              name: grafana-cloud-credentials
              namespace: monitoring

        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            secret:
              create: false
              name: grafana-cloud-credentials
              namespace: monitoring
          - name: grafana-cloud-logs
            type: loki
            secret:
              create: false
              name: grafana-cloud-credentials
              namespace: monitoring

      clusterMetrics:
        enabled: true
        kepler:
          enabled: true
        opencost:
          enabled: false
          metricsSource: grafana-cloud-metrics
          opencost:
            exporter:
              defaultClusterId: "{cluster-name}"
            prometheus:
              existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
              external:
                url: "{prometheus-url}/api/prom"
      clusterEvents:
        enabled: true
      podLogs:
        enabled: true
      alloy-metrics:
        enabled: true
      alloy-singleton:
        enabled: true
      alloy-logs:
        enabled: true
