---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-ca
  namespace: mysql-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  isCA: true
  commonName: mysql-ca
  secretName: mysql-ca-secret
  duration: 87600h # 10 years
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mysql-ca-issuer
  namespace: mysql-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ca:
    secretName: mysql-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-server-cert
  namespace: mysql-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  secretName: mysql-ssl-certs
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - mysql
  commonName: mysql
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - mysql
    - mysql.mysql-operator
    - mysql.mysql-operator.svc
    - mysql.mysql-operator.svc.cluster.local
    - "*.mysql-operator"
    - "*.mysql-operator.svc"
    - "*.mysql-operator.svc.cluster.local"
  issuerRef:
    name: mysql-ca-issuer
    kind: Issuer
